// venues.js — central config for all venues
module.exports = [
  {
    id:      'bellevue',
    name:    'Bellevue Gardens',
    short:   'Bellevue',
    prefix:  'BLV',
    address: '140 Woburn Rd · Lower Hutt',
    phone:   '04 569 7010',
    tagline: 'Around the corner in Lower Hutt since 1917.',
    discounts: { jug: '$1.50', pint: '50c' },
    colors: {
      bg:       '#f1ead0',
      paper:    '#fbf7e8',
      primary:  '#097d4c',
      dark:     '#053b27',
      mid:      '#2a9966',
      accent:   '#ef90be',
      tan:      '#e6dcb5',
      ink:      '#1a1a17',
      inkMid:   '#3a3a35',
      inkLight: '#6b6b62',
    }
  },
  {
    id:      'metro',
    name:    'Metro Sports Bar',
    short:   'Metro',
    prefix:  'MET',
    address: 'Porirua',
    phone:   '',
    tagline: 'Live sport. Cold beer. Your local.',
    discounts: { jug: '$1.50', pint: '50c' },
    colors: {
      bg:       '#f5e6d0',
      paper:    '#f5e6d0',
      primary:  '#8b0000',
      dark:     '#8b0000',
      mid:      '#a52020',
      accent:   '#f5e6d0',
      tan:      '#ddd0bc',
      ink:      '#2a0000',
      inkMid:   '#4a1010',
      inkLight: '#7a3030',
    }
  },
  {
    id:      'bedrocks',
    name:    'Bedrocks Bar',
    short:   'Bedrocks',
    prefix:  'BDR',
    address: 'Lower Hutt',
    phone:   '',
    tagline: 'Solid drinks. Good times.',
    discounts: { jug: '$1.50', pint: '50c' },
    colors: {
      bg:       '#fdf6e3',
      paper:    '#fdf6e3',
      primary:  '#8b6914',
      dark:     '#8b6914',
      mid:      '#a07820',
      accent:   '#d4a843',
      tan:      '#e8d9b0',
      ink:      '#2a1f00',
      inkMid:   '#4a3800',
      inkLight: '#7a6020',
    }
  },
  {
    id:      'sportys',
    name:    "Sporty's Bar",
    short:   'Sportys',
    prefix:  'SPT',
    address: 'Palmerston North',
    phone:   '',
    tagline: 'The home of live sport.',
    discounts: { jug: '$1.50', pint: '50c' },
    colors: {
      bg:       '#f0f4f8',
      paper:    '#ffffff',
      primary:  '#1a5276',
      dark:     '#0d2d40',
      mid:      '#2980b9',
      accent:   '#27ae60',
      tan:      '#d5e8f0',
      ink:      '#1a1a1a',
      inkMid:   '#444444',
      inkLight: '#777777',
    }
  },
  {
    id:      'office',
    name:    'The Office Bar',
    short:   'The Office',
    prefix:  'OFF',
    address: 'Newtown',
    phone:   '',
    tagline: 'Work can wait.',
    discounts: { jug: '$1.50', pint: '50c' },
    colors: {
      bg:       '#e8eef4',
      paper:    '#e8eef4',
      primary:  '#7199bc',
      dark:     '#7199bc',
      mid:      '#8ab0d0',
      accent:   '#6b5529',
      tan:      '#c8d8e8',
      ink:      '#1a2a3a',
      inkMid:   '#2a3a4a',
      inkLight: '#4a6070',
    }
  }
];
